remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Learn To Theme
author:
  name: Saltssaumure
  url: https://github.com/Saltssaumure

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/title.png

github:
  owner_url: https://github.com/Saltssaumure
  owner_name: Saltssaumure